#! /bin/sh

sxhkd &
feh --bg-scale Downloads/Background.png
libinput-gestures-setup autostart
libinput-gestures-setup start
polybar mybar &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2 
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_paddig 31
 
bspc config urgent_border_color "#9e0909"

bspc config left_padding 2
bspc config right padding 2
bspc config bottom_padding 2
