#!/bin/sh

# This is the example configuration file for river(1).
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the riverctl(1) man page for complete documentation

# Compose Key
XKB_DEFAULT_VARIANT=caps:compose

# Use the "logo" key as the primary modifier
[ "$XDG_SESSION_TYPE" = "x11" ] && mod="Mod1" || mod="Mod4"

# Mod+Q to close the focused view
riverctl map normal $mod+Shift Q close

# Mod+E to exit river

riverctl map normal $mod D spawn "tofi-drun"
riverctl map normal $mod+Shift D spawn "tofi-run"

# Mod+J and Mod+K to focus the next/previous view in the layout stack
riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

# Mod+Shift+J and Mod+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

# Mod+Period and Mod+Comma to focus the next/previous output
riverctl map normal $mod period focus-output next
riverctl map normal $mod comma focus-output previous

# Mod+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal $mod+Shift period send-to-output next
riverctl map normal $mod+Shift comma send-to-output previous

# Mod+Return to bump the focused view to the top of the layout stack
riverctl map normal $mod+Control Return zoom

# Mod+H and Mod+L to decrease/increase the main factor by 5%
# If using rivertile(1) this determines the width of the main stack.
riverctl map normal $mod H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $mod L send-layout-cmd rivertile "main-ratio +0.05"

# Mod+Shift+H and Mod+Shift+L to increment/decrement the number of
# main views in the layout
riverctl map normal $mod+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal $mod+Shift L send-layout-cmd rivertile "main-count -1"

# Mod+Alt+{H,J,K,L} to move views
riverctl map normal $mod+Mod1 H move left 100
riverctl map normal $mod+Mod1 J move down 100
riverctl map normal $mod+Mod1 K move up 100
riverctl map normal $mod+Mod1 L move right 100

# Mod+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal $mod+Mod1+Control H snap left
riverctl map normal $mod+Mod1+Control J snap down
riverctl map normal $mod+Mod1+Control K snap up
riverctl map normal $mod+Mod1+Control L snap right

# Mod+Alt+Shif+{H,J,K,L} to resize views
riverctl map normal $mod+Mod1+Shift H resize horizontal -100
riverctl map normal $mod+Mod1+Shift J resize vertical 100
riverctl map normal $mod+Mod1+Shift K resize vertical -100
riverctl map normal $mod+Mod1+Shift L resize horizontal 100

# Mod + Left Mouse Button to move views
riverctl map-pointer normal $mod BTN_LEFT move-view

# Mod + Right Mouse Button to resize views
riverctl map-pointer normal $mod BTN_RIGHT resize-view

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Mod+[1-9] to focus tag [0-8]
    riverctl map normal $mod "$i" set-focused-tags $tags

    # Mod+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal $mod+Shift "$i" set-view-tags $tags

    # Mod+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal $mod+Shift+Control "$i" toggle-focused-tags $tags

    # Mod+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal $mod+Control "$i" toggle-view-tags $tags
done

# Mod+0 to focus all tags
# Mod+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 9) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags
riverctl map normal $mod+Shift 0 set-view-tags $all_tags

# Mod+Space to toggle float
riverctl map normal $mod+Shift Space toggle-float

# Mod+F to toggle fullscreen
riverctl map normal $mod F toggle-fullscreen

# Mod+{Up,Right,Down,Left} to change layout orientation
riverctl map normal $mod Up send-layout-cmd rivertile "main-location top"
riverctl map normal $mod Right send-layout-cmd rivertile "main-location right"
riverctl map normal $mod Down send-layout-cmd rivertile "main-location bottom"
riverctl map normal $mod Left send-layout-cmd rivertile "main-location left"

# Mod+S to change to Full layout
riverctl map normal $mod S layout full

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Mod+F11 to enter passthrough mode
riverctl map normal $mod F11 enter-mode passthrough

# Mod+F11 to return to normal mode
riverctl map passthrough $mod F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive
    riverctl map $mode None XF86Eject spawn "eject -T"

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  	spawn "pamixer -i 5"
    riverctl map $mode None XF86AudioLowerVolume  	spawn "pamixer -d 5"
    riverctl map $mode None XF86AudioMute         	spawn "pamixer --toggle-mute"
    riverctl map $mode $mod+Shift Up 		  	spawn "pamixer -i 5"
    riverctl map $mode $mod+Shift Down  	  	spawn "pamixer -d 5"
    riverctl map $mode $mod+Shift Left         		spawn "pamixer --toggle-mute"
    riverctl map $mode $mod+Shift Right         	spawn "pamixer --toggle-mute"

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn "playerctl play-pause"
    riverctl map $mode None XF86AudioPlay  spawn "playerctl play-pause"
    riverctl map $mode None XF86AudioPrev  spawn "playerctl previous"
    riverctl map $mode None XF86AudioNext  spawn "playerctl next"

    # Control screen backlight brighness with light (https://github.com/haikarainen/light)
    riverctl map $mode None XF86MonBrightnessUp   spawn "light -A 5"
    riverctl map $mode None XF86MonBrightnessDown spawn "light -U 5"
done

# Set repeat rate
riverctl set-repeat 50 300

# Set the layout on startup
riverctl spawn rivertile
riverctl default-layout rivertile

# Set app-ids of views which should float
riverctl float-filter-add "float"
riverctl float-filter-add "popup"

# Set app-ids of views which should use client side decorations
riverctl csd-filter-add "gedit"

# Set opacity and fade effect
# riverctl opacity 1.0 0.75 0.0 0.1 20

###
### 	My programs
###

# audio setup
ponymix -d alsa_input.usb-Logitech_Logitech_USB_Headset_000000000000-00.mono-fallback set-default &
ponymix -d alsa_output.usb-Logitech_Logitech_USB_Headset_000000000000-00.analog-stereo set-default &
ponymix --card alsa_card.pci-0000_01_05.1 set-profile  output:hdmi-stereo &

# Bars
waybar  &
# yambar &
foot &
# Deamons
dunst &
greenclip daemon&
# Autentification Deamon
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1&
lxpolkit &

riverctl focus-follows-cursor normal
riverctl float-filter-add title lxsession-logout


##################################
### Application lauch bindings ###
##################################

# Mod+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
riverctl map normal $mod Return spawn foot
riverctl map normal $mod+Shift Return spawn alacritty

riverctl map normal $mod W spawn "wayland-screenshot"
riverctl map normal $mod apostrophe spawn "foot vi"
riverctl map normal $mod backslash spawn "foot htop"
riverctl map normal $mod semicolon spawn "foot vifm"
riverctl map normal $mod+Control P spawn "PASSWORD_STORE_DIR='$XDG_DATA_HOME/pass' passmenu"
riverctl map normal $mod+Shift F spawn qutebrowser
riverctl map normal $mod+Shift L spawn "~/Downloads/Code/MyFiles/.local/bin/rofishutdown.sh"
riverctl map normal $mod+Shift P spawn "playerctl play-pause"
riverctl map normal $mod+Shift+Control L spawn "swaylock -lkKc \#000000"
riverctl map normal $mod+Shift+Control S spawn "shutdown 0"
riverctl map normal $mod+Shift+Control+Alt L spawn "swaylock -lkKc \#000000 & systemctl hybrid-sleep"
riverctl map normal None Print spawn "wayland-screenshot"


#### Input Configuration ####

riverctl keyboard-layout -options compose:caps,shift:both_capslock us

# Doen't seam to work
riverctl keyboard-group-create normal
riverctl keyboard-group-add normal 113-49948-Logitech_USB_Keyboard
riverctl keyboard-group-add normal 1-1-AT_Translated_Set_2_Keyboard

## Touchpad configuration ##

riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad click-method clickfinger
riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad drag enabled
riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad middle-emulation enabled
riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad natural-scroll disabled
riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad tap enabled
riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad tap-button-map left-right-middle
riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad scroll-method two-finger



sleep 2s

# start thing on the other monitor

displays=$(wlr-randr | grep -c '"')
[ "$displays" -ge 2 ]&&
	riverctl focus-output next &&
	# yambar &
wlr-randr --output HDMI-A-1 --pos 0,0 --output LVDS-1 --pos 1920,312
