# Typical laptop setup, with wifi, brightness, battery etc, for
# i3/Sway.

# For X11/i3, you'll want to replace calls to swaymsg with i3-msg, and
# the sway-xkb module with the xkb module.

# fonts we'll be re-using here and there
awesome: &awesome Font Awesome 5 Free:style=solid:pixelsize=14
awesome_brands: &awesome_brands Font Awesome 5 Brands:pixelsize=16

std_underline: &std_underline {underline: { size: 2, color: ff0000ff}}

# This is THE bar configuration
bar:
  height: 26
  location: top
  spacing: 5
  margin: 7

  # Default font
  font: Adobe Helvetica:pixelsize=12

  foreground: ffffffff
  background: 111111cc

  border:
    width: 1
    color: 999999cc
    margin: 5
    top-margin: 0

  left:
    - river:
        title:
            string:
                {text: "{seat} - {title}"}
        content:
          list:
            items:
              - map:
                  tag: visible
                  values:
                    false:
                      empty: {}
                    true:
                      string:
                        text: "{id}"
                        deco:
                          underline:
                            size: 1
                            color: 00ffffcc

              - map:
                  tag: focused
                  values:
                    false:
                      empty: {}
                    true:
                      string:
                        text: "{id}"
                        deco:
                          underline:
                            size: 1
                            color: ff000088

              - map:
                  tag: occupied
                  values:
                    false:
                      empty: {}
                    true:
                      string:
                        text: "{id}"
                        deco:
                          underline:
                            size: 1
                            color: ffffff88



  center:
          - clock:
                content:
                    - string: {text: , font: "Font Awesome 5 Free:style=solid:size=12"}
                    - string: {text: "{date}", right-margin: 5}
                    - string: {text: , font: "Font Awesome 5 Free:style=solid:size=12"}
                    - string: {text: "{time}"}

  right:
    - removables:
        content:
          map:
            tag: optical
            values:
              true:
                string:
                  text: " "
                  font: *awesome
              false:
                string:
                  text: " {device} {label}"

    - network:
        name: enp5s0
        content:
          map:
            tag: carrier
            values:
              false: {empty: {}}
              true:
                map:
                  tag: state
                  default: {string: {text: , font: *awesome, foreground: ffffff66}}
                  values:
                    up:
                      map:
                        tag: ipv4
                        default: {string: {text: , font: *awesome}}
                        values:
                          "": {string: {text: , font: *awesome, foreground: ffffff66}}

    - network:
        name: wlp4s0
        content:
          map:
            tag: state
            default: {string: {text: , font: *awesome, foreground: ffffff66}}
            values:
              down: {string: {text: , font: *awesome, foreground: ff0000ff}}
              up:
                map:
                  tag: ipv4
                  default: {string: {text: , font: *awesome}}
                  values:
                    "": {string: {text: , font: *awesome, foreground: ffffff66}}

    - clock:
        time-format: "%H:%M %Z"
        content:
          - string: {text: , font: *awesome}
          - string: {text: "{date}", right-margin: 5}
          - string: {text: , font: *awesome}
          - string: {text: "{time}"}

    - label:
        content:
          string:
            on-click: "lxsession-logout"
            text: 
            font: *awesome
