#! /bin/sh

# Desktops

[ $(xrandr -q | grep "connected" | grep -v "disconnected" | wc -l) = 1 ] &&
bspc monitor -d I II III IV V VI VII VIII IX X XI XII ||
bspc monitor LVDS -d I II III IV V &&
bspc monitor VGA-0 -d I II III IV V VI VII
~/.local/bin/polybar_lounch.sh

# Config

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc desktop -f '^12'
bspc desktop -l next
alacritty -e calcurse &
alacritty -e neomutt &
sleep 2s
bspc desktop -f '^1'

# Ruls

bspc rule -a Geary:geary desktop='^12'
bspc rule -a Microsoft\ Teams\ -\ Preview:\* desktop='^12'
bspc rule -a Zathura:org.pwmt.zathura state=tiled

# Autostart

# teams &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1&
dunst &
feh --bg-scale Downloads/BG.png
lxpolkit &
numlockx on
pasystray &
sxhkd &
# volctl &
pa-applet &

