#! /bin/sh

# Desktops

	[ "$(xrandr -q | grep "connected" | grep -v "disconnected" | wc -l)" = 1 ] &&
	bspc monitor -d I II III IV V VI VII VIII IX X XI XII ||
	autorandr -c
	SCREENS=$(xrandr | grep 'connected' | grep -v 'disconnected' | awk '{print $1}' | sort)
	SCRNUMBER=$(echo "$SCREENS" | wc -l)
	[ "$SCRNUMBER" = 1 ] && bspc monitor -d I II III IV V VI VII VIII IX X XI XII ||
	if  [ "$SCRNUMBER" = 2 ]; then
		Exactmoddel="$(xrandr | grep 'connected' | grep -v 'disconnected' | awk '{print $1}' | sort | tr -t '\n' ' ')"
		bspc monitor "$(echo $Exactmoddel  | awk '{print $1}')" -d I II III IV V VI && bspc monitor "$(echo $Exactmoddel | awk '{print $2}')" -d I II III IV V VI

		autorandr --load Prim
	fi

# Polybar?
	if type "xrandr"; then
		for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
			MONITOR=$m polybar --reload mybarBa &
		done
	else
		polybar ---reload mybarBa &
	fi
#More Config
feh --bg-scale Downloads/BG.png
numlockx on
ponymix --card alsa_card.pci-0000_01_05.1 set-profile  output:hdmi-stereo



# Config

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc desktop -f '^12'
sleep 2s
bspc desktop -f '^1'
bspc rule -a Zathura:org.pwmt.zathura state=tiled

# Autostart

dunst &
lxpolkit &
dxhd &
alacritty &

setxkbmap -option compose:caps,shift:both_capslock
xinput set-prop "SynPS/2 Synaptics TouchPad" 309 {1,1}
xinput set-prop "SynPS/2 Synaptics TouchPad" 293 {0,0,0,0,1,3,2}
xinput set-prop "SynPS/2 Synaptics TouchPad" 317 {0,0,0,0,1,3,2}
xinput set-prop "SynPS/2 Synaptics TouchPad" 319 {0,0,0,0,1,3,2}
